name: monorepo-split

on:
  push:
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - hewcode-laravel
          - hewcode-react
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'

      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'hewcode'
          repository_name: '${{ matrix.package }}'
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'github-actions'
          user_email: 'actions@github.com'